language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rocketeer55-github"
    token:
      secure: "7362552b36bd27b76a88495b55f817d78b045d2a"
jdk:
  - oraclejdk9
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
